name: Build and deploy ASP.Net Core app to Azure Web App - visingsobiodlarna-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp" --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B590E657D08149D1BB16B9ECFC678FA2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4B0A33D35E434648852F630D5E25CBAC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0BCFDCDC2E9144D18D70A0E84B0ACE18 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'visingsobiodlarna-api'
          slot-name: 'Production'
          package: .
